version: '3.7'
services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    command: postgres -c listen_addresses='*'

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PG_ADMIN_PORT}:80
    restart: unless-stopped

  api:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PORT=${API_PORT}
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '${API_PORT}:${API_PORT}'
